In [1]:
import pandas as pd

In [2]:
s=pd.Series([10, 20, 30, 40, 50])

In [3]:
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
print(s[0])

10

Custom index

In [5]:
s= pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])

In [6]:
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
print(s["a"])

10

In [8]:
print(s[0])

10

C:\Users\DELL\AppData\Local\Temp\ipykernel_1872\287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

Series from Dictionary

In [9]:
data = {"Math":90,"physics":85,"chemistry":88}

In [10]:
marks = pd.Series(data)

In [11]:
print(data)

{'Math': 90, 'physics': 85, 'chemistry': 88}

In [12]:
print(marks)

Math         90
physics      85
chemistry    88
dtype: int64

Data Frames in pandas

In [13]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Marks": [85, 90, 88]
}

In [14]:
print(data)

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Marks': [85, 90, 88]}

In [15]:
type(data)

dict

In [16]:
marks = pd.DataFrame(data)

In [17]:
print(marks)

      Name  Age  Marks
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88

In [18]:
marks = pd.DataFrame(
    data,
    index = ["Student1", "Student2", "Student3"])

In [19]:
print(marks)

             Name  Age  Marks
Student1    Alice   25     85
Student2      Bob   30     90
Student3  Charlie   35     88

In [20]:
marks.set_index("Name", inplace=True)

In [21]:
print(marks)

         Age  Marks
Name
Alice     25     85
Bob       30     90
Charlie   35     88

In [25]:
df=pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie","Hairish","Hemanth"],
    "Age": [25, 30, 35, 28,67],
    "Marks": [85, 90, 88, 92,89]
})

In [23]:
print(df)

      Name  Age  Marks
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88

In [26]:
df.head(2)

    Name  Age  Marks
0  Alice   25     85
1    Bob   30     90

In [27]:
df.tail(2)

      Name  Age  Marks
3  Hairish   28     92
4  Hemanth   67     89

In [29]:
df.shape

(5, 3)

In [30]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [32]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   37.000000  88.800000
std    17.161002   2.588436
min    25.000000  85.000000
25%    28.000000  88.000000
50%    30.000000  89.000000
75%    35.000000  90.000000
max    67.000000  92.000000

Selecting the data

In [33]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3    Hairish
4    Hemanth
Name: Name, dtype: object

In [34]:
df[["Name","Marks"]]

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     88
3  Hairish     92
4  Hemanth     89

In [35]:
df[df["Marks"]>85]

      Name  Age  Marks
1      Bob   30     90
2  Charlie   35     88
3  Hairish   28     92
4  Hemanth   67     89

In [36]:
df[(df["Marks"]>85) & (df["Age"]>30)]

      Name  Age  Marks
2  Charlie   35     88
4  Hemanth   67     89

Sorting+value Counts

In [37]:
df.sort_values("Marks")

      Name  Age  Marks
0    Alice   25     85
2  Charlie   35     88
4  Hemanth   67     89
1      Bob   30     90
3  Hairish   28     92

In [38]:
df.sort_values(by="Marks", ascending=False)

      Name  Age  Marks
3  Hairish   28     92
1      Bob   30     90
4  Hemanth   67     89
2  Charlie   35     88
0    Alice   25     85

In [39]:
df["Age"].value_counts()

Age
25    1
30    1
35    1
28    1
67    1
Name: count, dtype: int64

Handling missing values

In [41]:
df= pd.DataFrame({"Name": ["Alice", "Bob", "Charlie",None,"Hairish","Hemanth"], "Age": [25, 30, 35,None, 28,67],"Marks": [85, 90, 88, None, 92,89]})

In [42]:
df

      Name   Age  Marks
0    Alice  25.0   85.0
1      Bob  30.0   90.0
2  Charlie  35.0   88.0
3     None   NaN    NaN
4  Hairish  28.0   92.0
5  Hemanth  67.0   89.0

In [43]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False  False
3   True   True   True
4  False  False  False
5  False  False  False

In [45]:
df.isnull().sum()

Name     1
Age      1
Marks    1
dtype: int64

In [46]:
df.dropna()

      Name   Age  Marks
0    Alice  25.0   85.0
1      Bob  30.0   90.0
2  Charlie  35.0   88.0
4  Hairish  28.0   92.0
5  Hemanth  67.0   89.0

In [47]:
print(df)

      Name   Age  Marks
0    Alice  25.0   85.0
1      Bob  30.0   90.0
2  Charlie  35.0   88.0
3     None   NaN    NaN
4  Hairish  28.0   92.0
5  Hemanth  67.0   89.0

In [48]:
cleaned_data = df.dropna()

In [49]:
cleaned_data

      Name   Age  Marks
0    Alice  25.0   85.0
1      Bob  30.0   90.0
2  Charlie  35.0   88.0
4  Hairish  28.0   92.0
5  Hemanth  67.0   89.0