<a href="https://colab.research.google.com/github/hairishbabucse273/CSE-237_Exercise_Collection/blob/main/CSE273_Exercise04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:

# Task 1.1: Create the DataFrame
data = {
    "Name": ["Aman", "Saurav", "Karan", "Shubham", "Abhishek", None, "Sameer"],
    "Age": [22, 23, np.nan, 22, 25, 24, 26],
    "Marks": [85, np.nan, 88, 90, 56, 72, np.nan],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:

# Task 1.2: Basic Inspection

# 1. Shape of the dataset
df.shape

(7, 4)

In [ ]:

# 2. Data types of columns
df.dtypes

Name        object
Age        float64
Marks      float64
Subject     object
dtype: object

In [ ]:
# 3. Statistical summary
df.describe()

             Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [ ]:
#Selection & Aggregation
df_name_marks = df[["Name", "Marks"]]

In [ ]:
df_marks_gt_80 = df[df["Marks"]>80]

In [ ]:
df_age_marks = df[(df["Age"]>22)&(df["Marks"]>80)]

In [ ]:
subject_count = df.groupby("Subject").size()

In [ ]:
df_name_marks

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5      None   72.0
6    Sameer    NaN

In [ ]:
df_marks_gt_80

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

In [ ]:
df_age_marks

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [ ]:
subject_count

Subject
Chemistry    2
Math         3
Physics      2
dtype: int64

In [ ]:
#Sorting & Ranking
df_sorted = df.sort_values(by="Marks", ascending = False)

In [ ]:
top_2_scorers = df.nlargest(2, "Marks")

In [ ]:
lowest_scorer = df.nsmallest(1, "Marks")

In [ ]:
df_sorted

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5      None  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [ ]:
top_2_scorers

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math

In [ ]:
lowest_scorer

       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

In [ ]:
# 1. Total missing values per column
missing_per_column = df.isna().sum()

In [ ]:
# 2. Rows where Marks are missing
marks_missing = df[df["Marks"].isna()]

In [ ]:
# 3. Remove rows with any missing value
cleaned_df = df.dropna()

In [ ]:
# 4. Compare shapes
original_shape = df.shape
cleaned_shape = cleaned_df.shape

In [ ]:
missing_per_column

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [ ]:
marks_missing

     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry

In [ ]:
cleaned_df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math

GroupBy in Pandas

In [ ]:
data = {
    "Name": ["Aman", "Saurav", "Karan", "Shubham", "Abhishek", None, "Sameer"],
    "Age": [22, 23, np.nan, 22, 25, 24, 26],
    "Marks": [85, np.nan, 88, 90, 56, 72, np.nan],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]
}

In [ ]:
df.groupby('Subject')['Marks'].mean()

Subject
Chemistry    90.000000
Math         76.333333
Physics      72.000000
Name: Marks, dtype: float64

In [ ]:
df.groupby('Subject').size()

Subject
Chemistry    2
Math         3
Physics      2
dtype: int64

In [ ]:
df.groupby('Subject')['Marks'].agg(['mean','max','min', 'count'])

                mean   max   min  count
Subject
Chemistry  90.000000  90.0  90.0      1
Math       76.333333  88.0  56.0      3
Physics    72.000000  72.0  72.0      1

In [ ]:
df.groupby(['Subject','Age'])['Marks'].mean()

Subject    Age
Chemistry  22.0    90.0
           26.0     NaN
Math       22.0    85.0
           25.0    56.0
Physics    23.0     NaN
           24.0    72.0
Name: Marks, dtype: float64