<a href="https://colab.research.google.com/github/hairishbabucse273/CSE-237_Exercise_Collection/blob/main/CSE273_Exercise05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Create DataFrame
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", None, "Eve", "Frank", "Grace"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "IT", "Sales"],
    "Role": ["Developer", "Manager", "Analyst", "Executive", "Analyst", "Developer", "Manager"],
    "Experience": [3, 10, 5, 2, 4, 8, 12],
    "Salary": [60000, 90000, 70000, 50000, 65000, 85000, 95000],
    "Score": [4.2, 4.8, 4.0, np.nan, 3.9, 4.5, np.nan]
})

In [ ]:
# Basic inspection
df.shape

Name           object
Department     object
Role           object
Experience      int64
Salary          int64
Score         float64
dtype: object

In [ ]:
df.dtypes

Name           object
Department     object
Role           object
Experience      int64
Salary          int64
Score         float64
dtype: object

In [ ]:
# Missing value analysis
df.isna().sum()

Name          1
Department    0
Role          0
Experience    0
Salary        0
Score         2
dtype: int64

In [ ]:
# Employees per department
employees_per_dept = df.groupby("Department").size()

In [ ]:
# Average salary by department
avg_salary_dept = df.groupby("Department")["Salary"].mean()

In [ ]:
#Average salary by role
avg_salary_role = df.groupby("Role")["Salary"].mean()

In [ ]:
# Average performance score by department
avg_score_dept = df.groupby("Department")["Score"].mean()

In [ ]:
# Rows with missing names
missing_names = df[df["Name"].isna()]

In [ ]:
# New hires (missing score)
new_hires = df[df["Score"].isna()]

In [ ]:
employees_per_dept

Department
HR       2
IT       3
Sales    2
dtype: int64

In [ ]:
avg_salary_dept

Department
HR       77500.000000
IT       71666.666667
Sales    72500.000000
Name: Salary, dtype: float64

In [ ]:
avg_salary_role

Role
Analyst      67500.0
Developer    72500.0
Executive    50000.0
Manager      92500.0
Name: Salary, dtype: float64

In [ ]:
avg_score_dept

Department
HR       4.350000
IT       4.233333
Sales         NaN
Name: Score, dtype: float64

In [ ]:
missing_names

   Name Department       Role  Experience  Salary  Score
3  None      Sales  Executive           2   50000    NaN

In [ ]:
new_hires

    Name Department       Role  Experience  Salary  Score
3   None      Sales  Executive           2   50000    NaN
6  Grace      Sales    Manager          12   95000    NaN

In [ ]:
# 1. Average (mean) Salary for each Department
df.groupby("Department")["Salary"].mean()

Department
HR       77500.000000
IT       71666.666667
Sales    72500.000000
Name: Salary, dtype: float64

In [ ]:
# 2. Average (mean) Performance Score for each Role
df.groupby("Role")["Score"].mean()

Role
Analyst      3.95
Developer    4.35
Executive     NaN
Manager      4.80
Name: Score, dtype: float64

In [ ]:
#3. Count of actual (non-null) Performance Score entries for each Department
df.groupby("Department")["Score"].count()

Department
HR       2
IT       3
Sales    0
Name: Score, dtype: int64

In [ ]:
# 4. Total number of employee records (rows) in each Department
df.groupby("Department").size()

Department
HR       2
IT       3
Sales    2
dtype: int64

In [ ]:
# Multiple Aggregations

# 1. Salary summary by Department (mean, max, min, count)
df.groupby("Department")["Salary"].agg(["mean", "max", "min", "count"])

                    mean    max    min  count
Department
HR          77500.000000  90000  65000      2
IT          71666.666667  85000  60000      3
Sales       72500.000000  95000  50000      2

In [ ]:
# 2. Performance Score summary by Role (mean, max, min, count)
df.groupby("Role")["Score"].agg(["mean", "max", "min", "count"])

           mean  max  min  count
Role
Analyst    3.95  4.0  3.9      2
Developer  4.35  4.5  4.2      2
Executive   NaN  NaN  NaN      0
Manager    4.80  4.8  4.8      1

In [ ]:
# Grouping by Multiple Columns

# 3. Average Salary grouped by Department and Role
df.groupby(["Department", "Role"])["Salary"].mean()

Department  Role
HR          Analyst      65000.0
            Manager      90000.0
IT          Analyst      70000.0
            Developer    72500.0
Sales       Executive    50000.0
            Manager      95000.0
Name: Salary, dtype: float64

In [ ]:


# 4. Average Performance Score grouped by Department and Experience
df.groupby(["Department", "Experience"])["Score"].mean()

Department  Experience
HR          4             3.9
            10            4.8
IT          3             4.2
            5             4.0
            8             4.5
Sales       2             NaN
            12            NaN
Name: Score, dtype: float64